global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ci_cd_pipeline'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'build_metrics'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'deployment_metrics'
    static_configs:
      - targets: ['localhost:9200']

  - job_name: 'application_health'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-service:8000']
